# Configuration file for GitHub Pages

lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
title: Nikhil Abhiram's Portfolio
description: Professional portfolio showcasing experience, skills, and projects
plugins:
  - jekyll-seo-tag
